version: "3"

services:
  platform:
    container_name: platform
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: .env.example
#    command: yarn run dev
    ports:
      - 3000:3000